#docker-compose -f docker-compose.prod.yml up -d

version: '3.1'
services:
  frontend:
    image: krasnovnikita/bsa2021-perflow-frontend
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./env/frontend.env
    volumes:
      - /etc/letsencrypt/live/perflow.westeurope.cloudapp.azure.com/cert.pem:/etc/letsencrypt/live/perflow.westeurope.cloudapp.azure.com/cert.pem
      - /etc/letsencrypt/live/perflow.westeurope.cloudapp.azure.com/chain.pem:/etc/letsencrypt/live/perflow.westeurope.cloudapp.azure.com/chain.pem
      - /etc/letsencrypt/live/perflow.westeurope.cloudapp.azure.com/fullchain.pem:/etc/letsencrypt/live/perflow.westeurope.cloudapp.azure.com/fullchain.pem
      - /etc/letsencrypt/live/perflow.westeurope.cloudapp.azure.com/privkey.pem:/etc/letsencrypt/live/perflow.westeurope.cloudapp.azure.com/privkey.pem

  gateway:
    image: krasnovnikita/bsa2021-perflow-gateway
    ports:
      - '4201:4201'
    environment: 
      ASPNETCORE_URLS: http://+:4201
    env_file:
     - ./env/gateway.env

   # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
  emy-storage:
    image: addictedcs/soundfingerprinting.emy
    ports:
      - '3399:3399'
      - '3340:3340'

  perflow:
    image: krasnovnikita/bsa2021-perflow-api
    ports:
      - '4202:4202'
    depends_on:
     - "rabbitmq"
    environment: 
      ASPNETCORE_URLS: http://+:4202
    env_file:
     - ./env/perflow.env

  perflow-studio:
    image: krasnovnikita/bsa2021-perflow-studio-api
    ports:
      - '4203:4203'
    depends_on:
     - "rabbitmq"
    environment: 
      ASPNETCORE_URLS: http://+:4203
    env_file:
     - ./env/perflow-studio.env

  processor:
    image: krasnovnikita/bsa2021-perflow-processor
    env_file:
     - ./env/processor.env
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      WAIT_HOSTS: rabbitmq:5672
