name: perflow
description: Mobile app for Perflow

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.6

  logger: ^1.0.0
  http: ^0.13.3

  provider: ^5.0.0
  flutter_bloc: ^7.1.0
  get_it: ^7.2.0
  vrouter: ^1.2.0+11

  json_annotation: ^4.1.0
  freezed_annotation: ^0.14.3
  injectable: ^1.4.1

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  build_runner: ^2.1.1
  json_serializable: any
  freezed: ^0.14.2
  injectable_generator: ^1.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
