name: Build and deploy

on:
  push:
    branches: [ feature/ci ]

  workflow_dispatch:

jobs:
  build-gateway:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Gateway
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: .docker/Gateway.Dockerfile
          push: true
          tags: krasnovnikita/bsa2021-perflow-gateway:latest

  build-perflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Perflow
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: .docker/Perflow.Dockerfile
          push: true
          tags: krasnovnikita/bsa2021-perflow-api:latest

  build-perflow-studio:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Perflow Studio
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: .docker/Perflow.Studio.Dockerfile
          push: true
          tags: krasnovnikita/bsa2021-perflow-studio-api:latest

  build-processor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Processor
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: .docker/Processor.Dockerfile
          push: true
          tags: krasnovnikita/bsa2021-perflow-processor:latest

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build frontend
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: .docker/Frontend.Dockerfile
          push: true
          tags: krasnovnikita/bsa2021-perflow-frontend:latest
